Update start date on main page
galenguyer/rit-covid-dashboard pull request #7
Opened 2022-01-18 20:47 UTC by fdeitylink

The start date is outdated

2022-01-18 20:48 UTC, fdeitylink commented
@galenguyer plox

2022-01-19 23:48 UTC, galenguyer requested changes

2022-01-19 23:48 UTC, galenguyer commented on src/MainPage.js
> +                    Total Positive Cases Since January 11 (Second Day of Classes)
It's technically since Jan 10, the first day of classes, I just didn't get data for that day.

2022-01-20 01:54 UTC, galenguyer approved these changes

2022-01-20 01:54 UTC, merged